feat: enhance CI workflows with package info retrieval and improved notifications. Updated to match the freshest of standards

diff --git a/workflow-templates/1gp-ci.yml b/workflow-templates/1gp-ci.yml
--- a/workflow-templates/1gp-ci.yml
+++ b/workflow-templates/1gp-ci.yml
@@ -3,7 +3,7 @@ on:
   pull_request:
     branches:
       - release
-      - '*.*.x'
+      - "*.*.x"
 
   merge_group:
     types: [checks_requested]
@@ -26,57 +26,68 @@ on:
         type: boolean
         default: false
 
-  workflow_call:
-    inputs:
-      skip-validation:
-        description: |
-          ( true | false ) Whether to skip validation when creating the package version.
-          Default is to skip validation.
-        required: false
-        default: true
-        type: boolean
-
-      ref:
-        description: |
-          The branch to use for the workflow.
-          Defaults to the branch the workflow was triggered from.
-        required: false
-        type: string
-
-    outputs:
-      package-receipt:
-        description: ( markdown ) The GitHub Step Summary from CI-build-and-test.
-        value: ${{ jobs.CI-build-and-test.outputs.package-receipt }}
-
-      package-version-id:
-        description: The Package version id for the package version created.
-        value: ${{ jobs.CI-build-and-test.outputs.package-version-id}}
-
-      auto-promote:
-        description: Whether to auto promote the package
-        value: 'false'
+concurrency:
+  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
+  cancel-in-progress: ${{ github.ref != 'refs/heads/release' }}
 
 permissions:
   id-token: write # This is required for requesting the ID token for AWS actions
   contents: read # This is required for actions/checkout
 
-concurrency:
-  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
-  cancel-in-progress: ${{ github.ref != 'refs/heads/release' }}
-
 env:
-  DEVOPS_SCRIPTS_PATH: './devops-utility-belt/scripts'
+  COMMIT_SHA1: ${{ github.sha }}
+  DELIVERY_SCRIPTS_PATH: "./devops-utility-belt/scripts"
   GIT_BASE_BRANCH: ${{ github.base_ref }}
   GIT_BRANCH: ${{ github.head_ref }}
-  RELEASE_FULLNAME: nCino Companies House (UK)
   REPO_NAME: ${{ github.event.repository.name }}
 
 jobs:
-  Path-Filtering:
+  Get-Package-Info:
+    name: Get Package Info
+    runs-on: ubuntu-latest
     outputs:
-      apex-changed: ${{ steps.path-filtering.outputs.apex-changed }}
-      markdown-changed: ${{ steps.path-filtering.outputs.markdown-changed }}
-      non-markdown-changed: ${{ steps.path-filtering.outputs.non-markdown-changed }}
+      package-name: ${{ steps.get-package-info.outputs.package-name }}
+      package-namespace: ${{ steps.get-package-info.outputs.package-namespace }}
+      subscriber-package-id: ${{ steps.get-package-info.outputs.subscriber-package-id }}
+      sfdx-project-json: ${{ steps.get-package-info.outputs.sfdx-project-json }}
+    steps:
+      - uses: actions/create-github-app-token@v2
+        id: app-token
+        with:
+          app-id: ${{ vars.NCINO_CI_GH_APP_ID }}
+          owner: ${{ github.repository_owner }}
+          private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}
+
+      - name: Checkout Release
+        uses: actions/checkout@v5
+        with:
+          token: ${{ steps.app-token.outputs.token }}
+
+      - name: Get Package Info
+        id: get-package-info
+        run: |
+          set -e
+          echo "package-name=$(jq -r '.name' sfdx-project.json)" >> $GITHUB_OUTPUT
+          echo "package-namespace=$(jq -r '.namespace' sfdx-project.json)" >> $GITHUB_OUTPUT
+          echo "subscriber-package-id=$(jq -r '.plugins.subscriberPackageId' sfdx-project.json)" >> $GITHUB_OUTPUT
+          echo "sfdx-project-json=$(jq . -cr sfdx-project.json)" >> $GITHUB_OUTPUT
+
+      - name: Print Package Info
+        run: |
+          echo "PACKAGE_NAME: $PACKAGE_NAME"
+          echo "PACKAGE_NAMESPACE: $PACKAGE_NAMESPACE"
+          echo "SUBSCRIBER_PACKAGE_ID: $SUBSCRIBER_PACKAGE_ID"
+          echo "SFDX_PROJECT_JSON: $SFDX_PROJECT_JSON"
+        env:
+          PACKAGE_NAME: ${{ steps.get-package-info.outputs.package-name }}
+          PACKAGE_NAMESPACE: ${{ steps.get-package-info.outputs.package-namespace }}
+          SUBSCRIBER_PACKAGE_ID: ${{ steps.get-package-info.outputs.subscriber-package-id }}
+          SFDX_PROJECT_JSON: ${{ steps.get-package-info.outputs.sfdx-project-json }}
+
+  Path-Filtering:
+    needs: Get-Package-Info
+    outputs:
+      build-required: ${{ steps.set-build-required.outputs.build-required }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/create-github-app-token@v2
@@ -87,37 +98,56 @@ jobs:
           private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}
 
       - name: 🫥 Checkout repo 😐
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           token: ${{ steps.app-token.outputs.token }}
-          sparse-checkout: 'sfdx-project.json'
+          sparse-checkout: "sfdx-project.json"
 
-      - name: Get Namespace
-        id: get-namespace
-        run: echo "NAMESPACE=$(jq -r '.namespace' sfdx-project.json)" >> $GITHUB_OUTPUT
-
-      # Uses the action by @dorny to filter paths
-      # More info can be found at https://github.com/dorny/paths-filter
       - name: Run Path Filtering
         uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # current version 3.0.2
         id: path-filtering
         with:
           filters: |
-            apex-changed:
-              - "src/${{ steps.get-namespace.outputs.NAMESPACE }}/**/*.cls"
-              - "src/${{ steps.get-namespace.outputs.NAMESPACE }}/**/*.trigger"
-              - "src/${{ steps.get-namespace.outputs.NAMESPACE }}/**/*.component"
-              - "src/${{ steps.get-namespace.outputs.NAMESPACE }}/**/*.page"
-              - "src/${{ steps.get-namespace.outputs.NAMESPACE }}/**/*.*-meta.xml"
-            markdown-changed:
-              - '**/*.md'
+            packaged-changed:
+              - "src/${{ env.NAMESPACE }}/**"
             non-markdown-changed:
               - '!**/*.md'
-          list-files: 'json'
+            sfdx-project-changed:
+              - "sfdx-project.json"
+            package-lock-json-changed:
+              - "package-lock.json"
+          list-files: "json"
           token: ${{ steps.app-token.outputs.token }}
+        env:
+          NAMESPACE: ${{ needs.Get-Package-Info.outputs.package-namespace }}
 
-  CI-build-and-test:
+      - name: 👷🏼‍♂️ Set Build Required 👷🏼‍♂️
+        id: set-build-required
+        run: |
+          SFDX_PROJECT_CHANGED="${{ steps.path-filtering.outputs.sfdx-project-changed }}"
+          PACKAGE_LOCK_JSON_CHANGED="${{ steps.path-filtering.outputs.package-lock-json-changed }}"
+          PACKAGED_CHANGED="${{ steps.path-filtering.outputs.packaged-changed }}"
+          NON_MARKDOWN_CHANGED="${{ steps.path-filtering.outputs.non-markdown-changed }}"
+
+          if [[ "$SFDX_PROJECT_CHANGED" == "true" ]] || \
+              [[ "$PACKAGE_LOCK_JSON_CHANGED" == "true" ]] || \
+              [[ "$PACKAGED_CHANGED" == "true" && "$NON_MARKDOWN_CHANGED" == "true" ]]; then
+              BUILD_REQUIRED="true"
+          else
+              BUILD_REQUIRED="false"
+          fi
+
+          echo "SFDX_PROJECT_CHANGED: $SFDX_PROJECT_CHANGED"
+          echo "PACKAGE_LOCK_JSON_CHANGED: $PACKAGE_LOCK_JSON_CHANGED"
+          echo "PACKAGED_CHANGED: $PACKAGED_CHANGED"
+          echo "NON_MARKDOWN_CHANGED: $NON_MARKDOWN_CHANGED"
+          echo "Build required: $BUILD_REQUIRED"
+
+          echo "build-required=$BUILD_REQUIRED" >> $GITHUB_OUTPUT
+
+  Build-And-Test:
     needs: Path-Filtering
+    if: ${{ github.event_name != 'pull_request' || needs.Path-Filtering.outputs.build-required == 'true' }}
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -134,7 +164,7 @@ jobs:
           private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}
 
       - name: 🗃️ Checkout Repo 🗃️
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           token: ${{ steps.app-token.outputs.token }}
           ref: ${{ inputs.ref }}
@@ -147,9 +177,9 @@ jobs:
           ci-ncino-ssh-private-signing-key: ${{ secrets.CI_NCINO_SSH_PRIVATE_SIGNING_KEY }}
           ci-ncino-ssh-public-signing-key: ${{ secrets.CI_NCINO_SSH_PUBLIC_SIGNING_KEY }}
           dev-hub-auth-url: ${{ secrets.DEVOPS_DEV_HUB_AUTH_URL }}
-          ncino-cli-install: 'true'
+          ncino-cli-install: "true"
           op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
-          setup-1password: 'true'
+          setup-1password: "true"
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
           NPM_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
@@ -158,7 +188,6 @@ jobs:
       ######          🏗️ BUILD AND PACKAGE 📦          ######
       #######################################################
       - name: 🕵️‍♀️ Validate config XML 🕵️‍♀️
-        if: ${{ needs.Path-Filtering.outputs.non-markdown-changed == 'true' }}
         uses: ncino/action-validate-xml@v1
 
       # Uncomment if you have Angular or AngularJS jest tests
@@ -170,51 +199,39 @@ jobs:
       # - name: 🧑‍🎤 Run npm test:unit script 👩‍🎤
       #   run: npm run test:unit
 
-      - name: 👩‍🌾 Get orgfarm org 👨‍🌾
+      - name: 👩‍🌾 Get OrgFarm Org 👨‍🌾
         id: setup-org
-        if: ${{ needs.Path-Filtering.outputs.apex-changed == 'true' }}
         uses: ncino/action-org-setup/org-provision-action@v5
         with:
           clean-org: ${{ inputs.clean-org }}
           has-namespace: true
           github-token: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
-          orgfarm-api-key: '${{ secrets.ORG_FARM_API_KEY }}'
+          orgfarm-api-key: "${{ secrets.ORG_FARM_API_KEY }}"
           orgfarm-api-url: ${{ vars.ORGFARM_API_URL }}
           preserve-org: ${{ inputs.preserve-org }}
           sftd-api-key: ${{ secrets.SFTD_API_KEY }}
-          skip-npm-install: 'true'
-          skip-python-install: 'true'
+          skip-npm-install: "true"
+          skip-python-install: "true"
 
       - name: 🚢 Deploy source and encrypt 💼
-        if: ${{ needs.Path-Filtering.outputs.apex-changed == 'true' }}
         uses: ncino/action-org-setup/org-source-push-action@v5
 
       - name: 🧪 Force Apex Tests 🧪
-        if: ${{ needs.Path-Filtering.outputs.apex-changed == 'true' }}
-        uses: ncino/action-force-apex-tests@v4
+        uses: ncino/action-force-apex-tests@v5
         with:
           auth-url: ${{ steps.setup-org.outputs.auth-url }}
-          skip-python-install: 'true'
+          skip-python-install: "true"
 
       #######################################################
       ######         🧼 POST-BUILD CLEANUP 🧹          ######
       #######################################################
-      # 🏁 Artifact Upload Phase 🏁
-      - name: 🤙 Upload Artifact and trigger packaging 🏄‍♂️
-        if: ${{ github.ref_name == 'release' && success() }}
-        uses: ncino/action-aws/s3_trigger_pipeline@v3
-        with:
-          commit-sha1: ${{ env.COMMIT_SHA1 }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
-
       - name: 🧹 Post Build Cleanup 🧹
         if: always()
         continue-on-error: true
         uses: ncino/action-org-setup/org-cleanup-action@v5
         with:
           orgfarm-api-url: ${{ vars.ORGFARM_API_URL }}
-          orgfarm-api-key: '${{ secrets.ORG_FARM_API_KEY }}'
+          orgfarm-api-key: "${{ secrets.ORG_FARM_API_KEY }}"
           preserve-org: ${{ inputs.preserve-org }}
 
       - name: 📝 Export Summary 📝
